"""Add anomaly and anomaly_detail tables

Revision ID: 36fe78e65184
Revises: 4cb1c0062b80
Create Date: 2025-05-29 14:20:42.508401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36fe78e65184'
down_revision: Union[str, None] = '4cb1c0062b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'item_id', name='uq_anomaly_key')
    )
    op.create_index('ix_anomaly_area_id', 'anomalies', ['area_id'], unique=False)
    op.create_index('ix_anomaly_item_id', 'anomalies', ['item_id'], unique=False)
    op.create_table('anomaly_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anomaly_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('anomaly_date', sa.Date(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anomaly_id', 'anomaly_type', 'anomaly_date', name='uq_anomaly_detail_key')
    )
    op.create_index('ix_anomaly_detail_anomaly_id', 'anomaly_details', ['anomaly_id'], unique=False)
    op.create_index('ix_anomaly_detail_type', 'anomaly_details', ['anomaly_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_anomaly_detail_type', table_name='anomaly_details')
    op.drop_index('ix_anomaly_detail_anomaly_id', table_name='anomaly_details')
    op.drop_table('anomaly_details')
    op.drop_index('ix_anomaly_item_id', table_name='anomalies')
    op.drop_index('ix_anomaly_area_id', table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
