"""remove item price table currency_type column and change unit column to currency

Revision ID: 4ac12d38e131
Revises: 4f6c1c16a004
Create Date: 2025-05-26 11:17:43.721998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac12d38e131'
down_revision: Union[str, None] = '4f6c1c16a004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_prices', sa.Column('currency', sa.String(), nullable=True))
    op.drop_column('item_prices', 'currency_type')
    op.drop_column('item_prices', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_prices', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('item_prices', sa.Column('currency_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('item_prices', 'currency')
    # ### end Alembic commands ###
