"""add index and constraints

Revision ID: 4cb1c0062b80
Revises: 4ac12d38e131
Create Date: 2025-05-26 11:36:18.532237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb1c0062b80'
down_revision: Union[str, None] = '4ac12d38e131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_area_fao_code', 'areas', ['fao_code'], unique=False)
    op.create_unique_constraint('uq_price_index_key', 'food_price_index', ['area_id', 'year', 'month'])
    op.create_unique_constraint('uq_price_inflation_key', 'food_price_inflation', ['area_id', 'year', 'month'])
    op.create_unique_constraint('uq_item_price_key', 'item_prices', ['item_id', 'area_id', 'year'])
    op.create_index('ix_item_fao_code', 'items', ['fao_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_fao_code', table_name='items')
    op.drop_constraint('uq_item_price_key', 'item_prices', type_='unique')
    op.drop_constraint('uq_price_inflation_key', 'food_price_inflation', type_='unique')
    op.drop_constraint('uq_price_index_key', 'food_price_index', type_='unique')
    op.drop_index('ix_area_fao_code', table_name='areas')
    # ### end Alembic commands ###
