"""init

Revision ID: b6956bc803df
Revises: 
Create Date: 2025-05-25 14:25:34.137534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6956bc803df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fao_code', sa.Integer(), nullable=False),
    sa.Column('m49_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fao_code'),
    sa.UniqueConstraint('m49_code'),
    sa.UniqueConstraint('name'),
    schema='food'
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fao_code', sa.Integer(), nullable=False),
    sa.Column('cpc_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpc_code'),
    sa.UniqueConstraint('fao_code'),
    schema='food'
    )
    op.create_table('food_price_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('flag', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['food.areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='food'
    )
    op.create_table('food_price_inflation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('flag', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['food.areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='food'
    )
    op.create_table('item_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('currency_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['food.areas.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['food.items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='food'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_prices', schema='food')
    op.drop_table('food_price_inflation', schema='food')
    op.drop_table('food_price_index', schema='food')
    op.drop_table('items', schema='food')
    op.drop_table('areas', schema='food')
    # ### end Alembic commands ###
