"""add table pipeline_progress

Revision ID: eeb4c04f49ef
Revises: 1fb8d8ecd03e
Create Date: 2025-06-09 11:14:27.276860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb4c04f49ef'
down_revision: Union[str, None] = '1fb8d8ecd03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('last_row_processed', sa.Integer(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('last_chunk_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_progress_table_name'), 'pipeline_progress', ['table_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_progress_table_name'), table_name='pipeline_progress')
    op.drop_table('pipeline_progress')
    # ### end Alembic commands ###
